import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import React from "react";
import {CartProvider} from "./contexts/CartContext"
import NavBar from "./components/header/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cardapio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
        <CartProvider>
          <NavBar />
          <main className="light text-foreground bg-background">{children}</main>
        </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
